'use strict';

var HashMap = require('hashmap');

var festival_map = new HashMap();

festival_map.set("Diwali","The festival of lights—Diwali or Deepavali—is the most popular festival in the Indian subcontinent. The underlying essence of Diwali revolves around light superseding darkness or figuratively, the triumph of goodness over evil. In that respect, glimmering diyas (lamps) adorn every nook and corners of the residence in the evening, followed by some fireworks and a delicious traditional banquet to top it all.");
festival_map.set("Holi","The vibrancy of Hindu festivals is largely owed to Holi, a festival of colors and a harbinger of spring in India. The onset of Holi is marked by the burning of an effigy of Holika—an evil entity from Hindu mythology—to signify the reign of good over evil. The night of revelry around the bonfire mostly goes on until the embers die. The following morning kicks off with smearing color powder on each other, more carousal and occasionally involves the consumption of bhang—an intoxicating edible cannabis preparation!");
festival_map.set("Onam","Onam is the official state festival of Kerala, celebrated with utmost fervor and festivities that include traditional sports like boat races and tug of war, among other things. The speculative legend behind the celebration of Onam is attributed to the homecoming of a demigod called Mahabali, likened to the legend of Holi festival and Holika. In both the cases, the celebration is owing to the triumph of hope over despair, although Mahabali is regarded with utmost respect as opposed to Holika. Onam is growing out of religious frontiers and establishing itself as a religiously diverse festival of Kerala.");
festival_map.set("Maha Shivaratri","Shiva is the foremost deity among the Hindu pantheon and regarded as the “destroyer.” Maha Shivaratri or “the great night of Shiva” is the night to commemorate the supremacy of Shiva by refraining from sleeping and instead praying to the great lord. Most dedicated disciples of Lord Shiva celebrate Maha Shivaratri by fasting and chanting the hymns to back the lord’s Tandava, a divine dance.");
festival_map.set("Krishna Janmashtami","Lord Krishna’s prominence in the Hindu folklore needs no addressing. Krishna Janmashtami is the joyous festival celebrating the birth of Krishna with a lot of merriment through dancing and singing. The gaiety of Krishna Janmastami is often accompanied by competitions, notably breaking the pot filled with yogurt suspended high in the air. Competitors form human pyramids in an attempt to break the pot and spill the contents, which is formally offered as prasada (ritualistic offering) subsequently.");
festival_map.set("Makar Sankranti","Conforming to the Hindu calendar, the sun enters the makara (capricorn) zodiac on the January 14 every year. Also, Surya (the sun god) is worshiped all across the country with unparalleled devotion on this day. Although this day is popularly known as Makar Sankranti, the nomenclature varies from state to state, as does the corresponding customs. Tamils call it Pongal, Assamese celebrate it as Bihu, and the better part of north Indians term it as Lohri. Regardless of the monikers, Makar Sankranti is a festival made unique by its celebrations, ranging from kite-flying to bonfires and extensive rituals on the river banks.");
festival_map.set("Ganesh Chaturthi","Ganesh Chaturti’s repute as one of the most popular festivals in the country is owed to its eccentricity, something the festival shares with its corresponding deity, Lord Ganesh. The deity in question, Ganesh, is the son of Lord Shiva, the destroyer. Yet, Ganesha is at odds with his father, by convictions and appearance. His face resembles that of an elephant, his witty and playful temperament inspires devotion from people of all age groups. Ganesh Chaturti commemorates the birth of Ganesh with formal offering of prayers to the clay idol of the deity. The idol is immersed in a water body amid festivities after a certain number of days.");
festival_map.set("Navratri","Akin to the recurring victory-of-good-over-evil trope in Hindu mythology, the legend behind Navratri festival has to do with Lord Rama’s triumph over Ravana, a demonic entity. Another alternative legend revolves around the victories of goddess Durga against the diabolical forces that walked the face of Earth. Navtari, meaning nine nights, is a period to honor the deities and plead for their blessings and goodwill. The invigorating festival centers around goddess Durga in the east India and goes by Durga Pooja. The world famous Dussehra of Mysore also falls on the final day of Navratri and the festival, as a whole, essentially serves as the precursor to the impending Diwali.");
festival_map.set("Rama Navami","The epic poem of Ramayana has vast religious significance in Hinduism. Its protagonist, Lord Rama, with his divine prowess and benevolence, slays the immoral beings, conquers the realm, and establishes order in the process. The day marking the birth of Lord Rama is celebrated as Rama Navami and the observances include charity, recitals, and prayers.");
festival_map.set("Ugadi","Conforming to the Hindu calendar, Ugadi is the new year’s day for Hindus. The festival of Ugadi is celebrated predominantly in the south Indian states of Karnataka, Andhra Pradesh, Tamilnadu, and the newly-formed Telangana. The premises are decorated with mango leaves, flowers, and other embellishments; floral patterns are drawn on the floor and savory snacks are prepared in a bid to welcome the new year on a high note. Additionally, the consumption of Bevu Bella—a blend of neem (bevu) and jaggery (bella)—is obligatory. Neem is bitter in taste and jaggery is sweet; together, they signify the acceptance of life’s bitterness and happiness in equal parts.");

festival_map.set("diwali","The festival of lights—Diwali or Deepavali—is the most popular festival in the Indian subcontinent. The underlying essence of Diwali revolves around light superseding darkness or figuratively, the triumph of goodness over evil. In that respect, glimmering diyas (lamps) adorn every nook and corners of the residence in the evening, followed by some fireworks and a delicious traditional banquet to top it all.");
festival_map.set("holi","The vibrancy of Hindu festivals is largely owed to Holi, a festival of colors and a harbinger of spring in India. The onset of Holi is marked by the burning of an effigy of Holika—an evil entity from Hindu mythology—to signify the reign of good over evil. The night of revelry around the bonfire mostly goes on until the embers die. The following morning kicks off with smearing color powder on each other, more carousal and occasionally involves the consumption of bhang—an intoxicating edible cannabis preparation!");
festival_map.set("onam","Onam is the official state festival of Kerala, celebrated with utmost fervor and festivities that include traditional sports like boat races and tug of war, among other things. The speculative legend behind the celebration of Onam is attributed to the homecoming of a demigod called Mahabali, likened to the legend of Holi festival and Holika. In both the cases, the celebration is owing to the triumph of hope over despair, although Mahabali is regarded with utmost respect as opposed to Holika. Onam is growing out of religious frontiers and establishing itself as a religiously diverse festival of Kerala.");
festival_map.set("maha shivaratri","Shiva is the foremost deity among the Hindu pantheon and regarded as the “destroyer.” Maha Shivaratri or “the great night of Shiva” is the night to commemorate the supremacy of Shiva by refraining from sleeping and instead praying to the great lord. Most dedicated disciples of Lord Shiva celebrate Maha Shivaratri by fasting and chanting the hymns to back the lord’s Tandava, a divine dance.");
festival_map.set("krishna janmashtami","Lord Krishna’s prominence in the Hindu folklore needs no addressing. Krishna Janmashtami is the joyous festival celebrating the birth of Krishna with a lot of merriment through dancing and singing. The gaiety of Krishna Janmastami is often accompanied by competitions, notably breaking the pot filled with yogurt suspended high in the air. Competitors form human pyramids in an attempt to break the pot and spill the contents, which is formally offered as prasada (ritualistic offering) subsequently.");
festival_map.set("makar sankranti","Conforming to the Hindu calendar, the sun enters the makara (capricorn) zodiac on the January 14 every year. Also, Surya (the sun god) is worshiped all across the country with unparalleled devotion on this day. Although this day is popularly known as Makar Sankranti, the nomenclature varies from state to state, as does the corresponding customs. Tamils call it Pongal, Assamese celebrate it as Bihu, and the better part of north Indians term it as Lohri. Regardless of the monikers, Makar Sankranti is a festival made unique by its celebrations, ranging from kite-flying to bonfires and extensive rituals on the river banks.");
festival_map.set("ganesh chaturthi","Ganesh Chaturti’s repute as one of the most popular festivals in the country is owed to its eccentricity, something the festival shares with its corresponding deity, Lord Ganesh. The deity in question, Ganesh, is the son of Lord Shiva, the destroyer. Yet, Ganesha is at odds with his father, by convictions and appearance. His face resembles that of an elephant, his witty and playful temperament inspires devotion from people of all age groups. Ganesh Chaturti commemorates the birth of Ganesh with formal offering of prayers to the clay idol of the deity. The idol is immersed in a water body amid festivities after a certain number of days.");
festival_map.set("navratri","Akin to the recurring victory-of-good-over-evil trope in Hindu mythology, the legend behind Navratri festival has to do with Lord Rama’s triumph over Ravana, a demonic entity. Another alternative legend revolves around the victories of goddess Durga against the diabolical forces that walked the face of Earth. Navtari, meaning nine nights, is a period to honor the deities and plead for their blessings and goodwill. The invigorating festival centers around goddess Durga in the east India and goes by Durga Pooja. The world famous Dussehra of Mysore also falls on the final day of Navratri and the festival, as a whole, essentially serves as the precursor to the impending Diwali.");
festival_map.set("rama navami","The epic poem of Ramayana has vast religious significance in Hinduism. Its protagonist, Lord Rama, with his divine prowess and benevolence, slays the immoral beings, conquers the realm, and establishes order in the process. The day marking the birth of Lord Rama is celebrated as Rama Navami and the observances include charity, recitals, and prayers.");
festival_map.set("ugadi","Conforming to the Hindu calendar, Ugadi is the new year’s day for Hindus. The festival of Ugadi is celebrated predominantly in the south Indian states of Karnataka, Andhra Pradesh, Tamilnadu, and the newly-formed Telangana. The premises are decorated with mango leaves, flowers, and other embellishments; floral patterns are drawn on the floor and savory snacks are prepared in a bid to welcome the new year on a high note. Additionally, the consumption of Bevu Bella—a blend of neem (bevu) and jaggery (bella)—is obligatory. Neem is bitter in taste and jaggery is sweet; together, they signify the acceptance of life’s bitterness and happiness in equal parts.");

festival_map.set("diwali","The festival of lights—Diwali or Deepavali—is the most popular festival in the Indian subcontinent. The underlying essence of Diwali revolves around light superseding darkness or figuratively, the triumph of goodness over evil. In that respect, glimmering diyas (lamps) adorn every nook and corners of the residence in the evening, followed by some fireworks and a delicious traditional banquet to top it all.");
festival_map.set("holi","The vibrancy of Hindu festivals is largely owed to Holi, a festival of colors and a harbinger of spring in India. The onset of Holi is marked by the burning of an effigy of Holika—an evil entity from Hindu mythology—to signify the reign of good over evil. The night of revelry around the bonfire mostly goes on until the embers die. The following morning kicks off with smearing color powder on each other, more carousal and occasionally involves the consumption of bhang—an intoxicating edible cannabis preparation!");
festival_map.set("onam","Onam is the official state festival of Kerala, celebrated with utmost fervor and festivities that include traditional sports like boat races and tug of war, among other things. The speculative legend behind the celebration of Onam is attributed to the homecoming of a demigod called Mahabali, likened to the legend of Holi festival and Holika. In both the cases, the celebration is owing to the triumph of hope over despair, although Mahabali is regarded with utmost respect as opposed to Holika. Onam is growing out of religious frontiers and establishing itself as a religiously diverse festival of Kerala.");
festival_map.set("maha shivaratri","Shiva is the foremost deity among the Hindu pantheon and regarded as the “destroyer.” Maha Shivaratri or “the great night of Shiva” is the night to commemorate the supremacy of Shiva by refraining from sleeping and instead praying to the great lord. Most dedicated disciples of Lord Shiva celebrate Maha Shivaratri by fasting and chanting the hymns to back the lord’s Tandava, a divine dance.");
festival_map.set("Krishna janmashtami","Lord Krishna’s prominence in the Hindu folklore needs no addressing. Krishna Janmashtami is the joyous festival celebrating the birth of Krishna with a lot of merriment through dancing and singing. The gaiety of Krishna Janmastami is often accompanied by competitions, notably breaking the pot filled with yogurt suspended high in the air. Competitors form human pyramids in an attempt to break the pot and spill the contents, which is formally offered as prasada (ritualistic offering) subsequently.");
festival_map.set("Makar sankranti","Conforming to the Hindu calendar, the sun enters the makara (capricorn) zodiac on the January 14 every year. Also, Surya (the sun god) is worshiped all across the country with unparalleled devotion on this day. Although this day is popularly known as Makar Sankranti, the nomenclature varies from state to state, as does the corresponding customs. Tamils call it Pongal, Assamese celebrate it as Bihu, and the better part of north Indians term it as Lohri. Regardless of the monikers, Makar Sankranti is a festival made unique by its celebrations, ranging from kite-flying to bonfires and extensive rituals on the river banks.");
festival_map.set("Ganesh chaturthi","Ganesh Chaturti’s repute as one of the most popular festivals in the country is owed to its eccentricity, something the festival shares with its corresponding deity, Lord Ganesh. The deity in question, Ganesh, is the son of Lord Shiva, the destroyer. Yet, Ganesha is at odds with his father, by convictions and appearance. His face resembles that of an elephant, his witty and playful temperament inspires devotion from people of all age groups. Ganesh Chaturti commemorates the birth of Ganesh with formal offering of prayers to the clay idol of the deity. The idol is immersed in a water body amid festivities after a certain number of days.");
festival_map.set("Navratri","Akin to the recurring victory-of-good-over-evil trope in Hindu mythology, the legend behind Navratri festival has to do with Lord Rama’s triumph over Ravana, a demonic entity. Another alternative legend revolves around the victories of goddess Durga against the diabolical forces that walked the face of Earth. Navtari, meaning nine nights, is a period to honor the deities and plead for their blessings and goodwill. The invigorating festival centers around goddess Durga in the east India and goes by Durga Pooja. The world famous Dussehra of Mysore also falls on the final day of Navratri and the festival, as a whole, essentially serves as the precursor to the impending Diwali.");
festival_map.set("Rama navami","The epic poem of Ramayana has vast religious significance in Hinduism. Its protagonist, Lord Rama, with his divine prowess and benevolence, slays the immoral beings, conquers the realm, and establishes order in the process. The day marking the birth of Lord Rama is celebrated as Rama Navami and the observances include charity, recitals, and prayers.");
festival_map.set("Ugadi","Conforming to the Hindu calendar, Ugadi is the new year’s day for Hindus. The festival of Ugadi is celebrated predominantly in the south Indian states of Karnataka, Andhra Pradesh, Tamilnadu, and the newly-formed Telangana. The premises are decorated with mango leaves, flowers, and other embellishments; floral patterns are drawn on the floor and savory snacks are prepared in a bid to welcome the new year on a high note. Additionally, the consumption of Bevu Bella—a blend of neem (bevu) and jaggery (bella)—is obligatory. Neem is bitter in taste and jaggery is sweet; together, they signify the acceptance of life’s bitterness and happiness in equal parts.");


module.exports = {

    fact : function(name){
        return festival_map.get(name);
    }

};